name: Auto Zip Release per Branch Esterni

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  poll-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Recupera lista completa branch dalla repo remota
      run: |
        > branches.txt

        PAGE=1
        while true; do
          RESPONSE=$(curl -s -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/InventivetalentDev/minecraft-assets/branches?per_page=100&page=$PAGE")

          COUNT=$(echo "$RESPONSE" | jq 'length')
          if [ "$COUNT" -eq 0 ]; then
            break
          fi

          echo "$RESPONSE" | jq -r '.[].name' >> branches.txt

          PAGE=$((PAGE+1))
        done

        echo "Branches trovati:"
        cat branches.txt

    - name: Confronta con lista precedente
      id: find_new
      run: |
        if [ ! -f .last_branches ]; then
          touch .last_branches
        fi

        comm -23 <(sort branches.txt) <(sort .last_branches) > new_branches.txt

        echo "Nuovi branch trovati:"
        cat new_branches.txt || true

        cp branches.txt .last_branches

    - name: Esci se nessun branch nuovo
      run: |
        if [ ! -s new_branches.txt ]; then
          echo "Nessun branch nuovo trovato. Esco."
          exit 0
        fi

    - name: Crea cartella per ZIP
      run: mkdir zips

    - name: Processa ogni branch nuovo
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        while read -r branch; do
          if [ -z "$branch" ]; then
            continue
          fi

          echo ""
          echo "========= Processing branch: $branch ========="

          # Verifica se esiste release con quel tag
          RELEASE_INFO=$(curl -s -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/$branch)

          RELEASE_ID=$(echo "$RELEASE_INFO" | jq -r '.id // empty')

          if [ -n "$RELEASE_ID" ]; then
            echo "Release con tag '$branch' già esistente, skippo."
            continue
          fi

          # Clona branch
          git clone --depth 1 --branch "$branch" \
            https://github.com/InventivetalentDev/minecraft-assets.git \
            "tmp-$branch"

          if [ -d "tmp-$branch/assets/minecraft/models" ]; then
            zip -r "zips/$branch-models.zip" -j tmp-$branch/assets/minecraft/models/*
            echo "ZIP creato: zips/$branch-models.zip"
          else
            echo "Directory assets/minecraft/models non trovata in $branch, skippo."
            rm -rf "tmp-$branch"
            continue
          fi

          rm -rf "tmp-$branch"

          # Crea release
          echo "Creo release con tag '$branch'..."
          RELEASE_RESPONSE=$(curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\":\"$branch\",\"name\":\"Models for $branch\",\"body\":\"Auto-generated release for branch $branch.\",\"draft\":false,\"prerelease\":false}")

          UPLOAD_URL=$(echo "$RELEASE_RESPONSE" | jq -r '.upload_url' | sed 's/{?name,label}//')

          if [ -z "$UPLOAD_URL" ] || [ "$UPLOAD_URL" = "null" ]; then
            echo "ERRORE: Creazione release fallita per $branch"
            echo "$RELEASE_RESPONSE"
            continue
          fi

          # Carica ZIP
          echo "Carico asset..."
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Content-Type: application/zip" \
            --data-binary @"zips/$branch-models.zip" \
            "$UPLOAD_URL?name=$branch-models.zip"

          echo "Release completata per $branch."
          echo "-----------------------------------"
        done < new_branches.txt
